// The plugin version.  This must match the version of the string files
VERSION(1.0)

// commands
STR(QUIT)
STR(QUIT_DESC)
STR(RESTART)
STR(RESTART_DESC)
STR(RECONFIG)
STR(RECONFIG_DESC)
STR(EDITFILE)
STR(EDITFILE_DESC)
STR(SHOWMENU)
STR(SHOWMENU_DESC)
STR(HIDEMENU)
STR(HIDEMENU_DESC)
STR(TOGGLETRAY)
STR(TOGGLETRAY_DESC)
STR(TOGGLESLIT)
STR(TOGGLESLIT_DESC)
STR(TOGGLEPLUGINS)
STR(TOGGLEPLUGINS_DESC)
STR(WORKSPACE)
STR(WORKSPACE_DESC)
STR(BROAM)
STR(BROAM_DESC)
STR(BROAM_EDIT)

// Edit Combo
STR(EDIT_SELECT)
STR(EDIT_STYLE)

// Menu Combo
STR(MENU_SELECT)
STR(MENU_MAIN)
STR(MENU_WORKSPACE)
STR(MENU_TOOLBAR)
STR(MENU_SYSTEMBAR)
STR(MENU_SLIT)

// Workspace Combo
STR(WORKSPACE_SELECT)
STR(WORKSPACE_LEFT)
STR(WORKSPACE_RIGHT)
STR(WORKSPACE_ADD)
STR(WORKSPACE_DEL)
STR(WORKSPACE_GATHER)
STR(WORKSPACE_MOVELEFT)
STR(WORKSPACE_MOVERIGHT)